author: Michel Lutz
author_url: https://twitter.com/michel_lutz
github_url: https://github.com/micheltlutz/MLBootstrap
root_url: https://micheltlutz.github.io/MLBootstrap/
module: MLBootstrap
output: docs
theme: fullwidth
xcodebuild_arguments: [-workspace, 'MLBootstrap.xcworkspace', -scheme, 'MLBootstrap-iOS']
