on: pull_request
name: Build
jobs:
  build:
    name: Build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=12.4,name=iPhone X']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Xcode-Select
        run: xcode-select -switch /Applications/Xcode_11.1.app
      - name: Build
        run: |
          xcodebuild clean build \
          -project MLBootstrap.xcodeproj \
          -scheme MLBootstrap-iOS \
          -destination "${destination}" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
  test:
    name: Test
    runs-on: macOS-10.14
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=12.4,name=iPhone X']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Xcode-Select
        run: xcode-select -switch /Applications/Xcode_11.1.app
      - name: Test
        run: |
          xcodebuild \
          -project MLBootstrap.xcodeproj \
          -scheme MLBootstrap-iOS \
          -sdk iphonesimulator \
          -destination "${destination}" \
          test
        env: 
         destination: ${{ matrix.destination }}
         after_success: |
          bash <(curl -s https://codecov.io/bash)
      - name: Upload coverage to Codecov  
        run: | 
          bash <(curl -s https://codecov.io/bash) -t ${{secrets.CODECOV_TOKEN}}
